version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /server
    ports:
      - 3000:3000
    environment: 
      - DB_NAME=mongotest
      - DB_CONNECTION=mongodb://adminuser:adminpass@db:27017
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./server-mongo
        target: /server
    command: bash -c "npm install && npm run dev" #npm start
  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=adminuser
      - MONGO_INITDB_DATABASE=mongotest
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
volumes:
  dbdata: