version: '3'
services:
  api:
    container_name: quiz_app_test_api
    # image: 'node:12.18.4'
    # working_dir: /server
    environment: 
      - DB_NAME=mongotest
      - DB_CONNECTION=mongodb://adminuser:adminpass@db:27017
      - NODE_ENV=test
    depends_on: 
      - db
    tty: true
    # volumes:
    #   - type: bind
    #     source: ./server-mongo
    #     target: /server
    #command: bash -c "npm install && npm run dev" #npm start
  db:
    # image: mongo:latest
    container_name: quiz_app_test_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      # - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=adminuser
      - MONGO_INITDB_DATABASE=mongotest
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
volumes:
  test_db:
networks:
  default:
    name: quiz_app_test